# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.05
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Vue Application
          command: npm run build

  push_dockerhub:
    docker:
      - image: cimg/base:2022.05
    steps:
      # - checkout
      - run: echo "Build and Push Docker Image"

workflows:
  # Name of workflow
  hello_and_goodbye:
    # List of jobs that will run
    jobs:
      - build
      - push_dockerhub:
          requires:
            - build
          filters:
            branches:
              only:
                - main